@startuml
skinparam style strictuml

actor Admin as A   
boundary "routes" as RO
boundary "vista roleAdmin.ejs" as V
control "roleAdmin.controller" as C
entity "Role.model" as R
entity "RolePrivilege.model" as RP
entity "Privilege.model" as P
entity "AccountRole.model" as AR
database "unitas_system" as BD
autonumber

activate A
A -> RO:GET/admin/roles
deactivate A
    activate RO
    RO -> C:getRoleAdmin(request,response)
    deactivate RO
        activate C
        C ->> R:fetchAll()
            activate R
            R->>BD:execute('SELECT * FROM role');
                activate BD
                BD-->R:roles
                deactivate BD
            R-->C:roles
            deactivate R
        C->>RP:fetchAll();
            activate RP
            RP-->BD:execute('SELECT * FROM roleprivilege');
                activate BD
                BD-->RP:role_privileges
                deactivate BD
            RP-->C:role_privileges
            deactivate RP
        C->>P:fetchAll();
            activate P
            P->>BD:execute('SELECT * FROM privilege');
                activate BD
                BD-->P:privileges
                deactivate BD
            P-->C:privileges
            deactivate P
            C->V: response.render('pages/admin-roles',\n{roles: roles, privileges:privileges, role_privileges:role_privileges, success: request.session.success ||''})
        deactivate C
    activate V
    V->A:HTML
    deactivate V


alt Any Query Failed
    activate C
    C->RO: response.render('/home',{error:error})
    deactivate C


end 

@enduml