@startuml
skinparam style strictuml

actor Admin as A   
boundary "vista roleAdmin.ejs" as V
boundary "routes" as RO
control "roleAdmin.controller" as C
entity "Role.model" as R
database "unitas_system" as BD
autonumber

activate A
A -> V: Clicks "Create Role" button.
deactivate A
    activate V
    V->V:createRole();
    V -> A: Show popup form.
    deactivate V

alt Cancel role creation
activate A
A->V: Clicks "Close" button.
deactivate A
    activate V
    V->V:closePopup();
    deactivate V
end

activate A
A->V: Clicks "Submit" button.
deactivate A
    activate V
    V->RO: GET /roleAdmin/newRole/:name
    deactivate V
        activate RO
        RO -> C: createRole(request, response);
        deactivate RO
            activate C
            create entity newRole as Role
            C->Role**:new Role(request.params.name);
            C->>Role: save();
                activate Role
                Role->>BD: execute('INSERT INTO role(role_id, name) VALUES(UUID(),?)',[name]);
                    activate BD
                    BD-->Role: Query OK
                    deactivate BD
                Role-->C: Query OK
                deactivate Role
            C->RO:response.redirect('admin/roles');
            deactivate C
            note right
            This redirects to page render 
            available in ADMIN-01
            end note
            
@enduml