@startuml
skinparam style strictuml

actor Admin as A   
boundary "vista roleAdmin.ejs" as V
boundary "routes" as RO
control "roleAdmin.controller" as C
entity "RolePrivilege.model" as RP
database "unitas_system" as BD
autonumber

activate A
A->V:Switches a privilege toggle at a privilege row and a role column.
deactivate A
    activate V
    V->V: Modifies toggle

opt Add privilege
    V->RO: fetch('admin/roles/add', \n{method:PATCH, headers:{'Accept': 'application/json'}, \nbody: JSON.stringify(privilege:privilege_id, role:role_id)};
    deactivate V
        activate RO
        RO->C: addPrivilegeRole(request,response) 
        deactivate RO
            activate C
            C->>RP: existsPrivilegeRole(role_id, privilege_id);
                activate RP
                RP->>BD: execute('SELECT * FROM roleprivilege as RP WHERE RP.role_id=? AND RP.privilege_id=?;',[role_id, privilege_id]);
                    activate BD
                    BD-->RP:relation
                    deactivate BD
                RP-->C:relation
                deactivate RP
            
            
    alt relation>0
            C->V: responde.status(500);
            deactivate C
        activate V
        V->A: Not changing view
        deactivate V
            
            activate C
    end  
            create entity newRolePrivilege as RolePrivilege
            C->RolePrivilege**: new RolePrivilege(role_id, privilege_id)
                activate RolePrivilege
            C->>RolePrivilege:save()
                    RolePrivilege->>BD:execute('INSERT INTO roleprivilege(role_id, privilege_id) VALUES(?,?)',[this.role_id, this.privilege_id])
                        activate BD
                            BD-->RolePrivilege: Query OK
                        deactivate BD
                        RolePrivilege-->C:Query OK
                deactivate RolePrivilege
            C->V:response.status(200);
            deactivate C

    alt 'RolePrivilege could not save'
            C->V:response.status(500);
            deactivate C
    activate V
    V->V: showErrorPopup(`Privilege ${privilege_id} could not be saved correctly to Role ${role_id}`);
    V->A: Returns toggle to previous position
    deactivate V
    end
end

    activate V
opt Remove Privilege
    V->RO: fetch('admin/roles/remove', \n{method:PATCH, headers:{'Accept': 'application/json'}, \nbody: JSON.stringify(privilege:privilege_id, role:role_id)};
    deactivate V
        activate RO
        RO->C: removePrivilegeRole(request,response) 
        deactivate RO
            activate C
            C->>RP: existsPrivilegeRole(role_id, privilege_id);
                activate RP
                RP->>BD: execute('SELECT * FROM roleprivilege as RP WHERE RP.role_id=? AND RP.privilege_id=?;',[role_id, privilege_id]);
                    activate BD
                    BD-->RP:relation
                    deactivate BD
                RP-->C:relation
                deactivate RP
            
            
    alt relation<0
            C->V: responde.status(500);
            deactivate C
        activate V
        V->A: Not changing view
        deactivate V
            
            activate C
    end  
            C->>RP: delete(role_id, privilege_id);
                activate RP
                    RP->>BD: execute('DELETE FROM roleprivilege as RP WHERE RP.role_id=? AND RP.privilege_id=?;',[role_id, privilege_id])
                    activate BD
                        BD-->RP: Query OK
                    deactivate BD
                RP-->C:Query OK
                deactivate RP

            C->V:response.status(200);
            deactivate C

    alt 'RolePrivilege could not remove'
            C->V:response.status(500);
            deactivate C
    activate V
    V->V: showErrorPopup(`Privilege ${privilege_id} could not be removed correctly from Role ${role_id}`);
    V->A: Returns toggle to previous position
    deactivate V
    end

end
@enduml