@startuml
skinparam style strictuml

actor User as U
boundary "auth.routes" as RO
boundary "view signin.ejs" as V
control "auth.controller" as C
entity "Employee.model" as EM
database "unitas_system" as BD
autonumber
activate U
U -> RO: GET /new
deactivate U
    activate RO
    RO -> C: getSignin(request, response)
    deactivate RO
        activate C
        C -> V: response.render('signin', {csrfToken: request.csrfToken()})
        deactivate C
    activate V
    V -> U: HTML form
    deactivate V

activate U
U -> RO: POST /new
deactivate U
    activate RO
    RO -> C: postSignin(request, response)
    deactivate RO
        activate C
        C -> C: fullname = request.body.name + " " + request.body.lastname
        C -> C: const employee_id = ''
        C -> EM: new Employee(fullname, request.body.names, request.body.lastnames)
            activate EM
            C ->> EM: save()
                EM ->> BD: execute('INSERT INTO employee(employee_id, full_name, names, lastnames) VALUES(UUID(),?,?,?)',[fullname, request.body.names, request.body.lastnames])
                    activate BD
                    BD --> EM: Query OK
                    deactivate BD
            EM --> C: employee saved
            deactivate EM
        C ->> EM: getEmployeeIdByFullname(fullname)
            activate EM
            EM ->> BD: execute('SELECT employee_id FROM employee WHERE full_name=?',[fullname])
                activate BD
                BD --> EM: employee_id
                deactivate BD
            EM --> C: Promise employee_id
            deactivate EM
        C -> C: employee_id = Employee.getEmployeeIdByFullname(fullname)
        C -> C: catch(error)
        C -> V: response.redirect('/')
        deactivate C
    activate V
    V -> U: Redirect /
    deactivate V

@enduml
