@startuml
skinparam style strictuml

actor Admin as A   
boundary "routes" as RO
boundary "vista roleAdmin.ejs" as V
control "roleAdmin.controller" as C
entity "Role.model" as R
entity "RolePrivilege.model" as RP
entity "Privilege.model" as P
entity "AccountRole.model" as AR
database "unitas_system" as BD
autonumber

activate A
A->V:Clicks "Delete" on a role
deactivate A
    activate V
    V->V:showConfirmPopup(roleId);
    deactivate V

activate A
opt Admin annotation
A->V:Clicks "Cancel" button
deactivate A
    activate V
    V->V:hidePopup();
    deactivate V
end
activate A

A->V:Clicks "Confirm" button
deactivate A
    activate V
    V->RO: DELETE /admin/roles/:roleId
    deactivate V
        activate RO
        RO->C:deleteRole(request, response);
        deactivate RO
            activate C
                C->>AR:updateByRole(delete_role_id);
                activate AR    
                    AR->>BD:execute('UPDATE accountrole SET role_id=? WHERE role_id=? values(?,?)'[ROLE_ID, delete_role_id]);
                    activate BD
                    BD-->AR:Query OK
                    deactivate BD
                AR-->C:Query OK
                deactivate AR

                C->>RP:deleteByRoleId(delete_role_id);
                    activate RP
                    RP-->BD:execute('DELETE FROM roleprivilege WHERE role_id=?',[delete_role_id]);
                        activate BD
                        BD-->RP:Query OK
                        deactivate BD
                    RP-->C:Query OK
                    deactivate RP

                C ->> R:delete(delete_role_id)
                    activate R
                    R->>BD:execute('DELETE FROM roles WHERE role_id=?',[delete_role_id]);
                        activate BD
                        BD-->R:Query OK
                        deactivate BD
                    R-->C:Query OK
                    deactivate R
                C->V:response.redirect('/admin/roles')
                deactivate C
            activate V
            
            group TEAM-01
            V->RO: GET/roleAdmin/:roleId
            deactivate V
                activate RO
                RO->C:getRoleAdmin(request,response)
                deactivate RO
                    activate C
                    note right
                    Role Administration Team Render
                    managed by the User Case TEAM-01
                    end note
                    C->V:response.render('pages/admin-roles',\n{roles: roles, privileges:privileges, role_privileges:role_privileges, success: request.session.success ||''})
                    deactivate C
                activate V
                V->A: HTML updated
                deactivate V

            end group
activate A

@enduml