@startuml
skinparam style strictuml

actor User as U
boundary "login.ejs" as V
boundary "home.ejs" as HV
boundary "auth.routes" as RO
boundary  "home.routes" as HR
control "auth.controller" as C
control "home.controller" as HC
entity "Account.model" as A
entity "Employee.model" as E
entity "bcryot" as BC
database "unitas_system" as BD

autonumber

activate U

note right
User enters the Unitas 
web application
end note

U->RO: GET /
deactivate U
    activate RO
    RO->C:getLogin(request,response)
    deactivate RO
        activate C
        C->V: esponse.render('pages/login.ejs',{...})
        deactivate C
    activate V
    V->U:HTML Login Form
    deactivate V
activate U
U -> V: Enters company email and password
U -> V: Clicks "Sign In" button
deactivate U

    activate V
    V -> RO: POST /
    deactivate V
        activate RO
        RO -> C: postLogin(request, response)
        deactivate RO

            activate C
            C->>A: fetchByEmail(request.body.email)
                activate A
                A->>BD: execute('SELECT * FROM account WHERE email=?',[email]);
                    activate BD
                    BD-->A: acccount_info
                    deactivate BD
                A-->C: account_info
                deactivate A
            
            C->>BC: compare(request.body.password, rows[0].password_hash)
                activate BC
                BC-->C:doMatch
                deactivate BC
            
            C->>E: getNamesByEmployeeId(rows[0].employee_id)
                activate E
                E->>BD: execute('SELECT names FROM employee WHERE employee_id=?',[employee_id]);
                    activate BD
                    BD-->E: names
                    deactivate BD
                BD-->C: names
                deactivate E

            C->>A: getPrivilegesFromAccountId(rows[0].account_id)
                activate A
                A->>BD: execute('SELECT P.privilege_id \nFROM privilege AS P \nINNER JOIN roleprivilege AS RP ON RP.privilege_id=P.privilege_id \nINNER JOIN role AS R ON R.role_id=RP.role_id \nINNER JOIN accountrole AS AR ON R.role_id= AR.role_id \nINNER JOIN account AS A ON AR.account_id=A.account_id \nWHERE A.account_id=?;',[account_id])
                    activate BD
                    BD-->A: privileges
                    deactivate BD
                A-->C: privileges
                deactivate A
            
alt Authentication failed
            C->RO: redirect('/')
            deactivate C

        activate RO
        RO->C:getLogin(request,response)
        deactivate RO

            activate C
            C->V: response.render('pages/login.ejs',{...})
    activate V
    V->U:HTML Login Form + Error message
    deactivate V
end
            
            C->HR: redirect('/home')
            deactivate C
    
    activate HR
    HR->HC: getHome(request,response)
    deactivate HR

        activate HC
        note right
        Section responsible for the 
        home.ejs render
        end note
        HC->HV: response.render('pages/home.ejs',{...});
        deactivate HC
    activate HV
    HV->U: HTML
    deactivate HV

@enduml