@startuml
skinparam style strictuml

actor User as U
boundary "routes" as RO
boundary "vista employeeList.ejs" as VL
boundary "vista employeeShow.ejs" as VS
control "employee.controller" as C
entity "Employee.model" as EM
entity "Activity.model" as ACM
entity "Team.model" as TM
entity "Project.model" as PM
database "unitas_system" as BD

activate U
U -> RO:GET /employees
deactivate U
    activate RO
    RO -> C:index(request, response)
    deactivate RO
        activate C
        C ->> EM:findAll()
            activate EM
            EM ->> BD:execute('SELECT * FROM employees')
                activate BD
                BD --> EM:rows
                deactivate BD
            EM --> C:employees
            deactivate EM
        
        alt no employees
            C -> VL:response.render('employees/index.ejs', {message: "No employees available"})
            deactivate C
                activate VL
                VL -> U:HTML + "No employees available" message
                deactivate VL
        
        else employees exist
            C -> VL:response.render('employees/index.ejs', {employees: employees})
            deactivate C
                activate VL
                VL -> U:HTML with employees list
                deactivate VL
        end

activate U
U -> VL:Clicks on an Employee
deactivate U
    activate VL
    VL -> RO:GET /employees/:id
    deactivate VL
        activate RO
        RO -> C:show(request, response)
        deactivate RO
            activate C
            C ->> EM:findById(id)
                activate EM
                EM ->> BD:execute('SELECT * FROM employees WHERE id=?', [id])
                    activate BD
                    BD --> EM:employee
                    deactivate BD
                EM --> C:employee
                deactivate EM
            
            alt not found / error
                C -> VL:response.render('employees/index.ejs', {error: "Profile could not be loaded"})
                deactivate C
                    activate VL
                    VL -> U:HTML + Error message
                    deactivate VL
            
            else found
                C ->> ACM:getActivities(employee_id)
                    activate ACM
                    ACM ->> BD:execute('SELECT * FROM activities WHERE employee_id=?', [employee_id])
                        activate BD
                        BD --> ACM:activities
                        deactivate BD
                    ACM --> C:activities
                    deactivate ACM
                
                C ->> TM:getTeams(employee_id)
                    activate TM
                    TM ->> BD:execute('SELECT t.* FROM teams t JOIN employee_teams et ON t.id = et.team_id WHERE et.employee_id=?', [employee_id])
                        activate BD
                        BD --> TM:teams
                        deactivate BD
                    TM --> C:teams
                    deactivate TM
                
                C ->> PM:getProjects(employee_id)
                    activate PM
                    PM ->> BD:execute('SELECT p.* FROM projects p JOIN employee_projects ep ON p.id = ep.project_id WHERE ep.employee_id=?', [employee_id])
                        activate BD
                        BD --> PM:projects
                        deactivate BD
                    PM --> C:projects
                    deactivate PM
                
                C -> VS:response.render('employees/show.ejs', {employee: employee, activities: activities, teams: teams, projects: projects})
                deactivate C
                    activate VS
                    VS -> U:HTML + Employee profile page
                    deactivate VS
            end

activate U

@enduml