@startuml
skinparam style strictuml

actor User as U
boundary "employeeDirectory.ejs" as ED
boundary "employeeDetails.ejs" as V
boundary "routes" as RO
control "employee.controller" as C
entity "project.model" as M
database "unitas_system" as DB

autonumber

activate U
U ->> ED: Accesses an Employee's page.
deactivate U

    activate ED
    ED->>RO:GET employee/:employee_id
    deactivate ED

        activate RO
        RO->C:getEmployeePage(request,response)
        deactivate RO
            activate C
            C->>M:getProjectByEmployeeId(employee_id)
                activate M
                M->>DB:execute(`SELECT P.project_id, P.name, P.description, P.status, P.start_date, P.end_date, P.employee_responsible_id,E.full_name,C.description as coll_description,C.started_at,C.ended_at\n FROM project as P \nINNER JOIN collaboration as C on P.project_id=C.project_id \nINNER JOIN employee as E ON P.employee_responsible_id=E.employee_id \nWHERE C.employee_id=?;`,\n[employee_id]);
                    activate DB
                    DB-->M: projects
                    deactivate DB
                M-->C:projects
                deactivate M
            C->V: response.render('pages/employeeDetails.ejs', {projects: projects})
        activate V
        V->U:HTML
        deactivate V

alt Render Failed
    C->RO: response.redirect('/employee')
    deactivate C
    activate RO
    RO->C:getEmployee(request,response)
    deactivate RO
        activate C
        note right
        Render of the Team Directory page + Error.
        end note
        C->ED:response.render('pages/employeeDirectory.ejs',{...}) 
        deactivate C
    activate ED
    ED->U: HTML+Error Message
    deactivate ED
end


@enduml