@startuml
skinparam style strictuml

actor User as U
boundary "routes" as RO
boundary "vista projectList.ejs" as VL
boundary "vista projectShow.ejs" as VS
control "project.controller" as C
entity "Project.model" as PM
entity "Achievement.model" as AM
database "unitas_system" as BD

activate U
U -> RO:GET /projects
deactivate U
    activate RO
    RO -> C:index(request, response)
    deactivate RO
        activate C
        C ->> PM:findAll()
            activate PM
            PM ->> BD:execute('SELECT * FROM projects')
                activate BD
                BD --> PM:rows
                deactivate BD
            PM --> C:projects
            deactivate PM
        
        alt no projects
            C -> VL:response.render('projects/index.ejs', {message: "No projects available"})
            deactivate C
                activate VL
                VL -> U:HTML + "No projects available" message
                deactivate VL
        
        else projects exist
            C -> VL:response.render('projects/index.ejs', {projects: projects})
            deactivate C
                activate VL
                VL -> U:HTML with projects list
                deactivate VL
        end

activate U
U -> VL:Clicks on a Project
deactivate U
    activate VL
    VL -> RO:GET /projects/:id
    deactivate VL
        activate RO
        RO -> C:show(request, response)
        deactivate RO
            activate C
            C ->> PM:findById(id)
                activate PM
                PM ->> BD:execute('SELECT * FROM projects WHERE id=?', [id])
                    activate BD
                    BD --> PM:project
                    deactivate BD
                PM --> C:project
                deactivate PM
            
            C ->> AM:getAchievements(project_id)
                activate AM
                AM ->> BD:execute('SELECT * FROM achievements WHERE project_id=?', [project_id])
                    activate BD
                    BD --> AM:achievements
                    deactivate BD
                AM --> C:achievements
                deactivate AM
            
            alt no achievements
                C -> VS:response.render('projects/show.ejs', {project: project, achievements: [], message: "No achievements for this project"})
                deactivate C
                    activate VS
                    VS -> U:HTML + Project details + "No achievements" message
                    deactivate VS
            
            else has achievements
                C -> VS:response.render('projects/show.ejs', {project: project, achievements: achievements})
                deactivate C
                    activate VS
                    VS -> U:HTML + Project details + Achievements section
                    deactivate VS
            end

activate U

@enduml