@startuml
skinparam style strictuml

actor Lead as L   
boundary "vista project.ejs" as V
boundary "project.routes" as RO
control "project.controller" as C
entity "Project.model" as P
database "unitas_system" as BD
autonumber

activate L
L ->> V:Click "Edit" button in the Information Module.
    activate V
    V->V: openPopup(project_id);
    V-->L: Updated View
    deactivate V

opt Cancel Edition
L ->> V: Click "Cancel" button
    activate V
    V -> V: closePopup(project_id);
    V-->L: Updated View
    deactivate V
end

L ->> V: Click "Save" button
    activate V
    V -> V: updateInfo(project_id);
    V ->> RO: fetch(`/project/info/${project_id}`, {method: PUT, headers:{'Accept': 'application/json'}, body: JSON.strinPify(data)});
        activate RO
            RO -> C: updateInfo(request, response);
        deactivate RO
            activate C
            C ->> P: updateInfo(project_id, name, description, status, end_date);
                activate P
                P->>BD: execute('UPDATE project SET name=?, description=?, status=?, end_date=? WHERE project_id=?',\n[name, description, status, end_date, project_id]);
                    activate BD
                    BD-->P: Query OK
                    deactivate BD
                P-->C: Query OK
                deactivate P
            C-->V: response.json({success:true});
    V->V: lockInputs(project_id);
    V->V: showSuccessPopup("Project updated successfully");
    V-->L: View updated

    alt Edition failed
                C-->V: response.json({success:false, error: error});        
            deactivate C
    V->V: lockInputs(project_id);
    V->V: showErrorPopup(error);
    V-->L: View updated
    deactivate V
    end
deactivate L    




@enduml
