@startuml
skinparam style strictuml

actor User as U
boundary "vista project.ejs" as V
boundary "project.routes" as RO
control "project.controller" as C
entity "Project.model" as ET
database "unitas_system" as BD
autonumber

activate U
U->RO: GET /project/:project_id
deactivate U
    activate RO
    RO -> C: getProjectPage(request, response)
    deactivate RO
        activate C
        note right: This function is used by multiple User Cases\n more internal functional calls may be before or after
        C->>ET: findById(project_id);
            activate ET
            ET->>BD: execute(`SELECT P.project_id,P.employee_responsible_id,P.name,P.description,P.status,P.start_date,P.end_date,P.created_at,NULL AS image,E.full_name AS lead_name\nFROM project AS P\nINNER JOIN employee AS E\nON E.employee_id = P.employee_responsible_id\nWHERE P.project_id = ?`,\n[project_id]);
                activate BD
                BD-->ET: projectRows
                deactivate BD
            ET-->C: projectRows
            deactivate ET
        C->V: response.render('project.ejs', { project: project })
        note right: Same render is returned by all User Cases, \n more parameters to render must be contemplated.
        deactivate C
    activate V
    V->U: HTML
    deactivate V

@enduml