@startuml
skinparam style strictuml

actor User as U
boundary "project_details.ejs" as V
boundary "routes" as RO
control "project.controller" as C
entity "Project.model" as M
database "unitas_system" as BD

autonumber
skinparam Style strictuml

actor User as U
boundary "projectDirectory.ejs" as PV
boundary "project.ejs" as V
boundary "project.routes" as RO
control "project.controller" as C
entity "collaboration.model" as P
database "unitas_system" as BD

autonumber

activate U
U->PV:Clicks on a project over the project directory page.
deactivate U
    activate PV
    PV->RO: GET project/:project_id
    deactivate PV
        activate RO
        RO->C: getProjectPage(request,response);
        deactivate RO
            activate C
                note right
                The information for the 
                initial page render is 
                obtained.
                end note
            C->V:response.render('pages/project.ejs',{...});
            deactivate C
    activate V
    V->U:HTML
    deactivate V
activate U
    group PROJ-07
    U->>RO:fetch('/project/:project_id/members',{method: GET, headers:{body:'application/json'}})
        activate RO
        RO->C:getProjectMembers(request,response)
        deactivate RO
        activate C
        C->>P:fetchDetailedByProject(project_id)
            activate P
            P->>BD:return db.execute(`SELECTC.collaboration_id,C.project_id,C.employee_id, C.description, C.started_at, C.ended_at, E.full_name \nFROM collaboration AS C \nLEFT JOIN employee AS E \nON E.employee_id = C.employee_id \nWHERE C.project_id = ?AND C.ended_at IS NULL \nORDER BY E.full_name ASC`,[project_id]);
                activate BD
                BD-->P:members
                deactivate BD
            P-->C:members
            deactivate P
        C-->U:response.status(200).json({success:true, body:members});
        end group

    U->U:generateMembers(members);
    U-->U: Updated view

alt Project Members Obtention Failed
    group PROJ-07 alt
        C-->U:response.status(500).json({success:false, message:error});     
        deactivate C
    end group
    U->U:showErrorPopup(error);
    U-->U:Updated view
end
deactivate U





@enduml