@startuml
skinparam style strictuml

actor Lead as L
boundary "vista project.ejs" as V
boundary "routes" as RO
control "project.controller" as C
entity "Goal.model" as G
database "unitas_system" as BD
autonumber

activate L
L ->> V:Click "Delete" button of a Project Goal.
    activate V
    V -> V: showConfirmationPopup(goal_id);
    V-->L:Updated view
    deactivate V


opt Cancel Elimination
L ->> V: Click "Cancel" button
    activate V
    V -> V: closePopup();
    V-->L:Updated view
    deactivate V
end

L ->> V: Click "Confirm" button
    activate V
    V -> V: deleteGoal(goal_id);
    V ->> RO: fetch(`/project/goal/${goal_id}`, {method: DELETE, headers:{'Accept': 'application/json'}})
        activate RO
            RO -> C: deleteGoal(request, response);
        deactivate RO
            activate C
            C ->> G: delete(goal_id);
                activate G
                G->>BD: execute('DELETE FROM goal WHERE goal_id=?',[goal_id]);
                    activate BD
                    BD-->G: Query OK
                    deactivate BD
                G-->C: Query OK
                deactivate G
                C-->V: return response.status(200).json({success:true});
    V->V: deleteGoalView(goal_id);
    V->V: showSuccessPopup("Goal deleted successfully");
    V->V: closePopup();
    V-->L: View updated

    alt Deletion failed
                C-->V: return response.status(500).json({success:false, message: error.stack});        
            deactivate C
    V->V: closePopup();
    V->V: showErrorPopup(error);    
    V-->L: View updated
    deactivate V
    end
deactivate L




@enduml