@startuml
skinparam style strictuml

actor Lead as L   
boundary "vista project.ejs" as V
boundary "project.routes" as RO
control "project.controller" as C
entity "Goal.model" as G
database "unitas_system" as BD
autonumber

activate L
L ->> V:Click "Edit" button of a Project Goal.
    activate V
    V -> V: openPopup(goal_id);
    V -->L: Updated view
    deactivate V


opt Cancel Edition
L ->> V: Click "Cancel" button
    activate V
    V -> V: closePopup(goal_id);
    V -->L: Updated view
    deactivate V
end

L ->> V: Click "Save" button
    activate V
    V -> V: updateGoal(goal_id);
    V ->> RO: fetch(`/project/goal/${goal_id}`, {method: PUT, headers:{'Accept': 'application/json'}, body: JSON.stringify(data)});
        activate RO
            RO -> C: updateGoal(request, response);
        deactivate RO
            activate C
            C ->> G: updateGoal(goal_id, title, description, due_date, status);
                activate G
                G->>BD: execute('UPDATE goal SET title=?, description=?, due_date=?, status=? WHERE goal_id=?',[title, description, due_date, status, goal_id]);
                    activate BD
                    BD-->G: Query OK
                    deactivate BD
                G-->C: Query OK
                deactivate G
            C-->V: response.json({success:true});
    V->V: lockInputs(goal_id);
    V->V: showSuccessPopup("Goal updated successfully");
    V-->L: View updated

    alt Edition failed
                C-->V: response.json({success:false, error: error});        
            deactivate C
    V->V: lockInputs(goal_id);
    V->V: showErrorPopup(error);
    V-->L: View updated
    deactivate V
    end
deactivate L




@enduml
