@startuml
skinparam style strictuml

actor User as U
boundary "view projectDirectory.ejs" as PV
boundary "view pages/project.ejs" as V
boundary "project.routes" as RO
control "project.controller" as C
entity "Achievement.model" as AM
database "unitas_system" as BD
autonumber

activate U
U -> PV: Clicks on a Project
deactivate U
    activate PV
    PV -> RO: GET /project/:project_id
    deactivate PV
        activate RO
        RO -> C: getProjectPage(request, response)
        deactivate RO
            activate C
            C -> V: response.render('pages/project', {...})
            deactivate C
    activate V
    V -> V: loadContent()
    group PROJ-12
    note right of V
        This AJAX function is reusable for
        other User Cases such as editing or
        deleting achievements.
    end note
    V -> RO: fetch('/project/:project_id/achievements', {method: GET, headers:{'Accept': 'application/json'}})
    deactivate V
        activate RO
        RO -> C: getProjectAchievements(request, response)
                deactivate RO
            activate C
            C ->> AM: fetchByProject(project_id)
                activate AM
                AM ->> BD: execute('SELECT A.achievement_id, A.project_id,\nA.employee_responsible_id, A.title, A.description,\nA.achievement_date, A.evidence_link, E.full_name\nFROM achievement AS A\nLEFT JOIN employee AS E ON E.employee_id = A.employee_responsible_id\nWHERE A.project_id = ?\nORDER BY A.achievement_date DESC, A.title ASC;', [project_id])
                    activate BD
                    BD --> AM: achievements
                    deactivate BD
                AM --> C: achievements
                deactivate AM
            C -> V: response.status(200).json({success:true, body: achievements})
            deactivate C
    activate V
    end group
    V -> V: generateAchievements(achievements)
    V -> U: HTML + Achievements section\n+ "No achievements for this project" message
    deactivate V

alt Project Achievements Obtention Failed
        activate C
    group PROJ-12 alt
        C -> V: response.status(500).json({success:false, message:error})
        deactivate C
    activate V
    end group
    V -> V: showErrorPopup(error)
    V -> U: HTML + Error popup\n+ Project view remains loaded
    deactivate V
end

@enduml
