@startuml
skinparam style strictuml

actor User as U
boundary "default.ejs" as V
boundary "report.routes" as RO
control "report.controller" as C
control "ai.wrapper" as W
entity "employee.model" as E
entity "project.model" as P
entity "team.model" as T
entity "activity.model" as A
entity "achievement.model" as AC
entity "goal.model" as G
entity "prompt.model" as PR
entity "report.model" as R
entity "ai.provider" as AIProvider
database "unitas_system" as BD

autonumber

activate U
U->>V:Click "Generate Report" button
note right
The validation of the Report model
are done within the inner JS of the
view before User Case.

Each modal is locked or open 
which gives a content type. 

end note
    activate V
    V->V:idenfityReportType();
    V->>RO: fetch(`/report/generate`, {method: POST, headers:{'Accept': 'application/json'}, body: JSON.stringify(data)})
        note right
        The data must contain all the filters of the report, 
        the content_id, and the page it was sent from
        end note
        activate RO
        RO->C: generateReport(request, response);
        deactivate RO
            activate C


            alt Employee Report
            C->>E: fetchById(employee_id)
                activate E
                E->>BD: execute('SELECT E.full_name, E.employee_id, A.slack_username, A.image, A.email FROM employee AS E INNER JOIN account AS A ON E.employee_id=A.employee_id WHERE E.employee_id=?',[employee_id])
                    activate BD
                    BD-->E: info
                    deactivate BD
                E-->C:info
                deactivate E

            C->>A: fetchByEmployeeBtw(employee_id, start_date, end_date)
                activate A
                A->>BD: execute('SELECT title, description, completed_at, project_id \nFROM activity \nWHERE employee_id=? AND completed_at BETWEEN ? AND ?',\n[employee_id, start_date, end_date])
                    activate BD
                    BD-->A: employee_activities
                    deactivate BD
                A-->C:employee_activities
                deactivate A

            C->>T: getEmployeeTeamsInfoBtw(employee_id, start_date, end_date)
                activate T
                T->>BD: execute('SELECT name, description \nFROM team AS T \nINNER JOIN employeeteam as ET ON ET.team_id=T.team_id \nWHERE ET.employee_id=? AND ET.joined_at >= ? AND \n(ET.left_at <= ? OR ET.left_at IS NULL);',\n[employee_id, start_date, end_date])
                    activate BD
                    BD-->T: teams_info
                    deactivate BD
                T-->C:teams_info
                deactivate T

            C->>A: getTeamActivitiesFromEmpBtw(employee_id,start_date, end_date)
                activate A
                A->>BD: execute('SELECT A.title, A.description, A.completed_at, A.employee_id, A.project_id \nFROM activity as A \nWHERE (A.completed_at BETWEEN ? AND ?) AND employee_id IN \n( SELECT ET.employee_id \nFROM employeeteam as ET \nWHERE ET.team_id \nIN( SELECT ET.team_id \nFROM employeeteam as ET \nWHERE ET.employee_id = ?));',\n[start_date, end_date, employee_id]);
                    activate BD
                    BD-->A: team_activities
                    deactivate BD
                A-->C:team_activities
                deactivate A
            
            C->>P: getEmployeeProjectsInfoBtw(employee_id, start_date, end_date)
                activate P
                P->>BD: execute('SELECT P.name, P.description, P.status, P.start_date, P.end_date \nFROM project as P \nINNER JOIN collaboration as C ON C.project_id=P.project_id \nWHERE C.employee_id=? AND C.started_at>=? \nAND (C.ended_at<=? OR C.ended_at IS NULL);'\n,[employee_id, start_date, end_date])
                    activate BD
                    BD-->P: employee_projects
                    deactivate BD
                P-->C:employee_projects
                deactivate P

            C->>A: getProjectActivitiesFromEmpBtw(employee_id, start_date, end_date)
                activate A
                A->>BD: execute('SELECT A.title, A.description, A.completed_at, A.project_id, A.employee_id \nFROM activity as A \nINNER JOIN collaboration as C ON A.project_id=C.project_id \nWHERE C.project_id IN\n( SELECT C.project_id \nFROM collaboration as C \nWHERE C.employee_id=? AND C.started_at>=? \nAND (C.ended_at<= ? OR C.ended_at IS NULL))',[employee_id, start_date, end_date])
                    activate BD
                    BD-->A: project_activities
                    deactivate BD
                A-->C:project_activities
                deactivate A

            C->>AC: getAchievementsFromEmp(employee_id, start_date, end_date)
                activate AC
                AC->>BD: execute('SELECT A.title, A.description, A.achievement_date, A.evidence_link, A.project_id \nFROM achievement as A \nINNER JOIN collaboration as C ON A.project_id=C.project_id \nWHERE C.employee_id=? AND C.started_at>=? \nAND (C.ended_at<= ? OR C.ended_at IS NULL);',[employee_id, start_date, end_date])
                    activate BD
                    BD-->AC: project_achievements
                    deactivate BD
                AC-->C:project_achievements
                deactivate AC

            C->>G: getGoalsFromEmp(employee_id)
                activate G
                G->>BD: execute('SELECT G.title, G.description, G.due_date, G.status, G.project_id \nFROM goal as G \nINNER JOIN collaboration as C ON G.project_id=C.project_id \nWHERE C.employee_id=? AND C.started_at>=? \nAND (C.ended_at<=? OR C.ended_at IS NULL);',\n[employee_id, start_date, end_date])
                    activate BD
                    BD-->G: project_goals
                    deactivate BD
                G-->C:project_goals
                deactivate G
            end

            alt Team Report

            C->>T: findById(team_id)
                activate T
                T->>BD: execute('SELECT * FROM team WHERE team_id = ?', [team_id]);
                    activate BD
                    BD-->T: team_info
                    deactivate BD
                T-->C:team_info
                deactivate T
            
            C->>A: getEmployeeActivitiesFromTeamBtw(team_id,start_date, end_date)
                activate A
                A->>BD: execute('SELECT A.title, A.description, A.completed_at, A.employee_id, A.project_id \nFROM activity as A \nWHERE (A.completed_at BETWEEN ? AND ?) AND employee_id IN \n(SELECT ET.employee_id \nFROM employeeteam as ET \nWHERE ET.team_id =?);',\n[start_date, end_date, team_id]);
                    activate BD
                    BD-->A: team_activities
                    deactivate BD
                A-->C:team_activities
                deactivate A
            
            C->>E: getEmployeeInfoFromTeam(team_id)
                activate E
                E->>BD: execute('SELECT E.full_name, ET.role \nFROM employee AS E \nINNER JOIN employeeteam AS ET ON E.employee_id=ET.employee_id \nWHERE ET.team_id=?;'\n,[team_id])
                    activate BD
                    BD-->E: employees_info
                    deactivate BD
                E-->C:employees_info
                deactivate E
            
            C->>P: getTeamProjectsInfoBtw(team_id, start_date, end_date)
                activate P
                P->>BD: execute('SELECT P.name, P.description, P.status, P.start_date, P.end_date FROM project as P INNER JOIN projectteam as PT ON P.project_id=PT.project_id WHERE PT.team_id=? AND PT.joined_at>=? AND PT.joined_at<=?;'\n,[team_id, start_date, end_date])
                    activate BD
                    BD-->P: team_projects
                    deactivate BD
                P-->C:team_projects
                deactivate P

            C->>A: getProjectActivitiesFromTeamBtw(team_id, start_date, end_date)
                activate A
                A->>BD: execute('SELECT A.title, A.description, A.completed_at, A.project_id, A.employee_id \nFROM activity as A \nINNER JOIN collaboration as C ON A.project_id=C.project_id \nWHERE C.project_id IN( \nSELECT PT.project_id \nFROM projectteam as PT \nWHERE PT.team_id = ? AND PT.joined_at>=? AND PT.joined_at<=?);',\n[team_id, start_date, end_date])
                    activate BD
                    BD-->A: project_activities
                    deactivate BD
                A-->C:project_activities
                deactivate A

            C->>AC: getAchievementsFromTeam(team_id, start_date, end_date)
                activate AC
                AC->>BD: execute('SELECT A.title, A.description, A.achievement_date, A.evidence_link, A.project_id \nFROM achievement as A \nINNER JOIN collaboration as C ON A.project_id=C.project_id \nWHERE C.project_id IN( \nSELECT PT.project_id \nFROM projectteam AS PT \nWHERE PT.team_id =? AND PT.joined_at>=? AND PT.joined_at<=?);',[team_id, start_date, end_date])
                    activate BD
                    BD-->AC: project_achievements
                    deactivate BD
                AC-->C:project_achievements
                deactivate AC

            C->>G: getGoalsFromTeam(team_id, start_date, end_date)
                activate G
                G->>BD: execute('SELECT G.title, G.description, G.due_date, G.status, G.project_id \nFROM goal as G \nINNER JOIN collaboration as C ON G.project_id=C.project_id \nWHERE C.project_id IN( \nSELECT PT.project_id \nFROM projectteam AS PT \nWHERE PT.team_id =? AND PT.joined_at>=? AND PT.joined_at<=?);',\n[employee_id, start_date, end_date])
                    activate BD
                    BD-->G: project_goals
                    deactivate BD
                G-->C:project_goals
                deactivate G
            end

            alt Project Report

            C->>P: getProjectInfo(project_id)
                activate P
                P->>BD: execute('SELECT P.name, P.description, P.status, P.start_date, P.end_date \nFROM project as P \nWHERE P.project_id = ?;'\n,[project_id])
                    activate BD
                    BD-->P: project_info
                    deactivate BD
                P-->C:project_info
                deactivate P
            
            C->>E: getEmployeeInfoFromTeam(project_id, start_date, end_date)
                activate E
                E->>BD: execute('SELECT E.full_name, C.description \nFROM employee AS E \nINNER JOIN collaboration AS C ON E.employee_id=C.employee_id \nWHERE C.project_id=? AND C.started_at>=? \nAND (C.ended_at<=? OR C.ended_at IS NULL);'\n,[project_id, start_date, end_date])
                    activate BD
                    BD-->E: employees_info
                    deactivate BD
                E-->C:employees_info
                deactivate E
            
            C->>A: getEmployeeActivitiesFromProjBtw(project_id, start_date, end_date)
                activate A
                A->>BD: execute('SELECT DISTINCT A.title, A.description, A.completed_at, A.employee_id, A.project_id \nFROM activity as A \nINNER JOIN collaboration AS C ON A.project_id=C.project_id \nWHERE (A.completed_at BETWEEN ? AND ?) \nAND C.project_id =?;',\n[start_date, end_date, project_id]);
                    activate BD
                    BD-->A: employee_activities
                    deactivate BD
                A-->C:employee_activities
                deactivate A

            C->>T: getTeamInfoFromProj(project_id, start_date, end_date)
                activate T
                T->>BD: execute('SELECT T.name, T.description \nFROM team AS T \nINNER JOIN projectteam as PT ON T.team_id=PT.team_id \nWHERE PT.project_id=? AND PT.joined_at>=? AND PT.joined_at<=?;',\n[project_id, start_date, end_date])
                    activate BD
                    BD-->T: team_info
                    deactivate BD
                T-->C:team_info
                deactivate T

            C->>A: getTeamActivitiesFromProjectBtw(project_id, start_date, end_date)
                activate A
                A->>BD: execute('SELECT DISTINCT A.title, A.description, A.completed_at, A.project_id, A.employee_id \nFROM activity as A \nINNER JOIN projectteam AS PT ON PT.project_id=A.project_id \nWHERE (A.completed_at BETWEEN ? AND ?) \nAND PT.project_id=?;',\n[start_date, end_date, project_id])
                    activate BD
                    BD-->A: team_activities
                    deactivate BD
                A-->C:team_activities
                deactivate A

            C->>AC: getAchievementsFromProj(project_id, start_date, end_date)
                activate AC
                AC->>BD: execute('SELECT A.title, A.description, A.achievement_date, A.evidence_link, A.project_id \nFROM achievement as A \nWHERE A.project_id=? AND A.achievement_date BETWEEN ? AND ?;',\n[project_id, start_date, end_date])
                    activate BD
                    BD-->AC: project_achievements
                    deactivate BD
                AC-->C:project_achievements
                deactivate AC

            C->>G: getGoalsFromProj(project_id, start_date, end_date)
                activate G
                G->>BD: execute('SELECT G.title, G.description, G.due_date, G.status, G.project_id FROM goal as G WHERE G.project_id=? AND G.created_at BETWEEN ? AND ?;', \n[project_id, start_date, end_date])
                    activate BD
                    BD-->G: project_goals
                    deactivate BD
                G-->C:project_goals
                deactivate G
            end

            alt Data Obtention Failed
            C-->V: response.status(500).json({success:false, message:'Data could not be obtained', error:error})
    V-->U:View (no changes)
            end

            note right
            body creation developed through the union of 
            the obtained queries and normalization.
            end note

            C->>PR: getPromptByType(report_type);
                activate PR
                    PR->>BD: execute(`SELECT P.description FROM prompt as P WHERE P.type=?`,[report_type])
                        activate BD
                        BD-->PR:prompt 
                        deactivate BD
                    PR-->C:prompt
                deactivate PR

            alt Data Obtention Failed
            C-->V: response.status(500).json({success:false, message:'Prompt could not be obtained', error:error})
    V-->U:View (no changes)
            end

            C->>W: generateReport(body, prompt);
                activate W
                note right
                Need to install ai & zod
                end note
                W->W: integratePrompt(body, prompt);
                W->W: getSchema(reportType);
                W->>AIProvider: streamText({model: openai("gpt-4o-mini"), output: Output.object({schema:schema}), prompt})
                    activate AIProvider
                    AIProvider-->W: API response
                    deactivate AIProvider
                W-->C: Report object
                deactivate W

            alt AI Response Failed
            C-->V: response.status(500).json({success:false, message:'API error', error:error})
    V-->U:View (no changes)
            end

            create entity ReportObject as ReportObject
            C->ReportObject**: new Report(generated_by_employee_id, content_id, content_type, prompt_id, period_start, period_end, content_json, filters_json, input_snapshop_json, model_name, model_version, ai_output_text)
                activate ReportObject
            C->>ReportObject:save()
                ReportObject->>BD:  execute(`\nINSERT INTO report(report_id,enerated_by_employee_id, content_id, \ncontent_type, prompt_id, period_start, period_end, created_at, content_json, filters_json, \ninput_snapshot_json, model_name, model_version, ai_output_text) \nVALUES(UUID(), ?,?,?,?,?,?,NOW(),?,?,?,?,?,?)`, \n[this.generated_by_employee_id, this.content_id, this.content_type, this.prompt_id, this.period_start,\n this.period_end, this.content_json, this.filters_json, this.input_snapshot_json, this.model_name, this.model_version, this.ai_output_text])}
                    activate BD
                    BD-->ReportObject: Query OK
                    deactivate BD
                ReportObject-->C: Query OK
                deactivate ReportObject
            
            alt Report Creation Failed
            C-->V: response.status(500).json({success:false, message:'Report could not be created', error:error})
    V-->U:View (no changes)
            end

            C->>R:fetchByContentId(employee_id, content_id)
                activate R
                R->>BD: execute(`SELECT *\nFROM report\nWHERE generated_by_employee_id = ?\nAND content_id = ?\nORDER BY created_at DESC\nLIMIT ?;`,\n[employee_id, content_id, limit],);
                    activate BD
                    BD-->R: latestReports
                    deactivate BD
                R-->C:latestReports
                deactivate R
            
            C-->V:response.status(200).json({success:true, latestReports: latestReports})
    V->V:updateLatestReports()
    V-->U: Updated view + Latest Report

            alt Report Obtention Failed
            C-->V: response.status(500).json({success:false, message:'Report could not be obtained', error:error})
    V-->U:View (no changes)
            end
            deactivate C
    deactivate V
deactivate U

@enduml