@startuml
skinparam style strictuml

actor User as U
boundary "vista team.ejs" as V
boundary "team.routes" as RO
control "team.controller" as C
entity "team.model" as ET
database "unitas_system" as BD
autonumber

activate U
U->RO: GET /team/:team_id
deactivate U
    activate RO
    RO -> C: getTeamPage(request, response)
    deactivate RO
        activate C
        note right: This function is used by multiple User Cases\n more internal functional calls may be before or after
        C->>ET: findById(team_id);
            activate ET
            ET->>BD: execute('SELECT * FROM team WHERE team_id = ?', [team_id]);                activate BD
                BD-->ET: teamInfo
                deactivate BD
            ET-->C: teamInfo
            deactivate ET
        C->V: response.render('team.ejs', { team })
        note right: Same render is returned by all User Cases, \n more parameters to render must be contemplated.
        deactivate C
    activate V
    V->U: HTML
    deactivate V

@enduml