@startuml
skinparam style strictuml

actor Lead as L
boundary "team.ejs" as V
boundary "team.routes" as RO
boundary "search.routes" as SR
control "team.controller" as C
entity "employee.model" as S
entity "employeeteam.model" as  ET
database "unitas_system" as BD

autonumber
activate L
L->>V: Click "Add" button
    activate V
    V->V: showSearchPopup();
    V-->L: Updated view
    deactivate V

alt Cancel Search Join
L->>V: Click "Close" button.
    activate V
    V->V: hidePopup();
    V-->L: Updated view
    deactivate V
end

    
group Search [Employee Search]
L->>V:User types name
    activate V
    V->V:validateInput();
    V->V:startEmployeeSearch(name);
    V->>SR:fetch('/search/employee/?name=${new URLSearchParams({n:name});}&page=${currentPage}', {method: 'GET', headers: { 'Accept': 'application/json'}});
        activate SR
        SR->C: getEmployeeSearchResult(request, results); 
        deactivate SR
            activate C
            C->>S: getEmployeeSearch(name, page, limit);
                activate S
                S->>BD: execute('SELECT employee_id, full_name AS label FROM employee WHERE LOWER(full_name) LIKE ?\n LIMIT ? OFFSET ?'\n,[normal_name, 11, offset]);
                    activate BD
                    BD-->S:results
                    deactivate BD
                S-->C: results
                deactivate S
            C-->V: response.json({body:results});
            deactivate C
    V->V:generateEmployeeResults(results);
    V-->L:updated view
    deactivate V

opt View More Results
L->>V: Clicks the "View More" button.
    activate V
    V->V:continueEmployeeSearch(name);
    V->>SR:fetch('/search/employee/?name=${new URLSearchParams({n:name});}&page=${currentPage}', {method: 'GET', headers: { 'Accept': 'application/json'}});
        activate SR
        SR->C: getEmployeeSearchResult(request, results); 
        deactivate SR
            activate C
            C->>S: getEmployeeSearch(name, page, limit);
                activate S
                S->>BD: execute('SELECT employee_id, full_name AS label FROM employee WHERE LOWER(full_name) LIKE ?\n LIMIT ? OFFSET ?'\n,[normal_name, 11, offset]);
                activate BD
                    BD-->S:results
                    deactivate BD
                S-->C: results
                deactivate S
            C-->V: response.json({body:results});
            deactivate C
    V->V:generateResults(results);
    V-->L:updated view
    deactivate V
end
L->>V: Click on a matching result
    activate V
end

    V->V: showRolePopup();
    V-->L: Updated view
    deactivate V

alt Cancel Role Join
L->>V: Click "Close" button.
    activate V
    V->V: hidePopup();
    V-->L: Updated view
    deactivate V
end




L->>V: Click "Submit" button.
    activate V
    V->V: addEmployeeTeam(team_id, employee_id, role)
    V->>RO: fetch('/team/join', {method:'POST', headers: { 'Accept': 'application/json'}, body:JSON.stringify({team_id= ..., employee_id: ..., role:...})})
        activate RO
        RO->C: addEmployeeTeam(request, response);
        deactivate RO
            activate C

            C->>ET:fetchByEmployeeAndTeam(employee_id, team_id)
                activate ET
                ET->>BD:execute(`SELECT * \nFROM employeeteam \nWHERE employee_id=? AND team_id=? AND left_at IS NULL;`,\n[employee_id, team_id]);
                    activate BD
                    BD-->ET: member
                    deactivate BD
                ET-->C:member
                deactivate ET
            
alt member>0
            C-->V: response.json({success:false, body:error});
    V->V: showFailingJoinMessage(team_id, employee_id, role, error);
    V-->L: Error message
end


            C->>ET: addEmployeeTeam(team_id, employee_id, role);
                activate ET
                ET->>BD: execute('INSERT INTO employeeteam(employee_id,team_id,joined_at,role) VALUES(?,?,NOW(),?)',[employee_id, team_id,role]);
                    activate BD
                    BD-->ET: Query OK
                    deactivate BD
                ET-->C: Query OK
                deactivate ET
            
            C->RO: response.redirect('/team/:team_id/members');
            deactivate C
        
        activate RO
        group 'TEAM-05'
        RO->C: getTeamMembers(request,response)
        deactivate RO
            activate C
            note right
            TEAM-05. 
            Consult Sequence Diagram
            end note
            C-->V: response.status(200).json({success:true, body:members});
        end group

    V->V: showTeamMembers(employees);
    V->V: showSuccessJoinMessage(team_id, employee_id, role);
    V-->L: Updated view + success message

alt Join Failed
            C-->V: response.json({success:false, body:error});
            deactivate C
    V->V: showFailingJoinMessage(team_id, employee_id, role, error);
    V-->L: Error message
    deactivate V
end
deactivate L

@enduml