@startuml
autonumber
skinparam Style strictuml

actor User as U
boundary "team.ejs" as V
boundary "team.routes" as RO
control "team.controller" as C
entity "team.model" as T
database "unitas_system" as BD

autonumber


activate U
U->PV:Clicks on a team over the team directory page.
deactivate U
    activate PV
    PV->RO: GET team/:team_id
    deactivate PV
        activate RO
        RO->C: getTeamPage(request,response);
        deactivate RO
            activate C
            note right
            The information for the 
            initial page render is 
            obtained.
            end note
            C->V:response.render('pages/team.ejs',{...});
            deactivate C
    activate V
    V->RO:fetch('/team/:team_id/members',{method: GET, headers:{body:'application/json'}})
    deactivate V
        activate C
        P->C:getProjectsByTeamId(teamId)
            activate P
            P->BD: execute('SELECT P.project_id, P.name, P.description, P.status, P.start_date, p.end_date, p.employee_responsible_id, E.full_name, PT.team_role \nFROM project as P \nINNER JOIN projectteam as PT ON PT.project_id=P.project_id \nINNER JOIN employee as E ON E.employee_id=P.employee_responsible_id \nWHERE PT.team_id=?;',[team_id]);
                activate BD
                
                deactivate BD
            deactivate P
        deactivate C






@enduml