@startuml
autonumber
skinparam Style strictuml

actor Lead as L
boundary "team.ejs" as V
boundary "team.routes" as RO
control "team.controller" as C
entity "team.model" as T
database "unitas_system" as BD

autonumber

activate L
L->V:Click on the "Delete Team" button
deactivate L
    activate V
    V->V:data-popup-open="delete-team-<%= team_id %>"
    V->L:Updated view
    deactivate V

alt Cancel deletion
activate L
L->V:Click on the "Cancel" button
deactivate L
    activate V
    V->V:data-popup-close
    V->L:Updated view
    deactivate V
activate L
end
L->V:Click on the "Delete" button
deactivate L
    activate V
    V->V:submit
    V->RO:fetch('/team/:team_id/delete',{method: DELETE, headers:{'Accept': 'application/json'}})
    deactivate V
        activate RO
        RO->C: deleteTeam(request, response);
        deactivate RO
            activate C
            C->>T:disableTeam(team_id);
                activate T
                T->>BD:execute('UPDATE team SET team.status='DISABLED' WHERE team.team_id=?;',[team_id])
                    activate BD
                    BD-->T: Query OK
                    deactivate BD
                T-->C: Query OK
                deactivate T

alt Deletion Failed
            C->V:response.json({success:false})
            deactivate C
    activate V
    V->V:data-popup-close
    V->L:Show unchanged view
    deactivate V
    activate C
end         

            C->RO: redirect('/team')
            deactivate C
    activate RO
    note right
        Render responsible under the 
        controller function getTeams.
    end note
    deactivate RO
            


            
    

@enduml