@startuml
skinparam style strictuml

actor User as U
boundary "routes" as RO
boundary "vista teamList.ejs" as VL
boundary "vista teamShow.ejs" as VS
control "team.controller" as C
entity "Team.model" as TM
entity "Project.model" as PM
database "unitas_system" as BD

activate U
U -> RO:GET /teams
deactivate U
    activate RO
    RO -> C:index(request, response)
    deactivate RO
        activate C
        C ->> TM:findAll()
            activate TM
            TM ->> BD:execute('SELECT * FROM teams')
                activate BD
                BD --> TM:teams
                deactivate BD
            TM --> C:teams
            deactivate TM
        
        alt no teams available
            C -> VL:response.render('teams/list.ejs', {teams: [], message: "No teams available"})
            deactivate C
                activate VL
                VL -> U:HTML + "No teams available" message
                deactivate VL
        
        else teams exist
            C -> VL:response.render('teams/list.ejs', {teams: teams})
            deactivate C
                activate VL
                VL -> U:HTML with teams list
                deactivate VL
        end

activate U
U -> VL:Clicks on a Team
deactivate U
    activate VL
    VL -> RO:GET /teams/:id
    deactivate VL
        activate RO
        RO -> C:show(request, response)
        deactivate RO
            activate C
            C ->> TM:findById(id)
                activate TM
                TM ->> BD:execute('SELECT * FROM teams WHERE id=?', [id])
                    activate BD
                    BD --> TM:team
                    deactivate BD
                TM --> C:team
                deactivate TM
            
            C ->> PM:findByTeamId(team_id)
                activate PM
                PM ->> BD:execute('SELECT p.* FROM projects p JOIN team_projects tp ON p.id = tp.project_id WHERE tp.team_id=?', [team_id])
                    activate BD
                    BD --> PM:projects
                    deactivate BD
                PM --> C:projects
                deactivate PM
            
            alt no projects associated
                C -> VS:response.render('teams/show.ejs', {team: team, projects: [], message: "This team has no associated projects"})
                deactivate C
                    activate VS
                    VS -> U:HTML + Team details + "This team has no associated projects" message
                    deactivate VS
            
            else projects exist
                C -> VS:response.render('teams/show.ejs', {team: team, projects: projects})
                deactivate C
                    activate VS
                    VS -> U:HTML + Team details + Team Projects section
                    deactivate VS
            end

activate U

@enduml