@startuml
skinparam style strictuml

actor User as U
boundary "team.ejs" as V
boundary "team.routes" as RO
control "team.controller" as C
entity "employeeteam.model" as  ET
database "unitas_system" as BD

autonumber
activate U
U->V: Click "Join" button
deactivate U
    activate V
    V->V: showRolePopup();
    V->U: Show popup
    deactivate V

alt Cancel Join
activate U
U->V: Click "Close" button.
deactivate U
    activate V
    V->V: hidePopup();
    deactivate V
end

activate U
U->V: Click "Submit" button.
deactivate U
    activate V
    V->V: addEmployeeTeam(team_id, employee_id, role)
    V->RO: fetch('/team/join', {method:'POST', headers: { 'Accept': 'application/json'}, body:JSON.stringify({team_id= ..., employee_id: ..., role:...})})
    deactivate V
        activate RO
        RO->C: addEmployeeTeam(request, response);
        deactivate RO
            activate C
            C->>ET:fetchByEmployeeAndTeam(employee_id, team_id)
                activate ET
                ET->>BD:execute(`SELECT * \nFROM employeeteam \nWHERE employee_id=? AND team_id=? AND left_at IS NULL;`,\n[employee_id, team_id]);
                    activate BD
                    BD-->ET: member
                    deactivate BD
                ET-->C:member
                deactivate ET
            
alt member>0
            C->V: response.json({success:false, body:error});
            deactivate C
    activate V
    V->V: showFailingJoinMessage(team_id, employee_id, role, error);
    V->U: Error message
    deactivate V
            activate C
end
            
            C->>ET: addEmployeeTeam(team_id, employee_id, role);
                activate ET
                ET->>BD: execute('INSERT INTO employeeteam(employee_id,team_id,joined_at,role) VALUES(?,?,NOW(),?)',[employee_id, team_id,role]);
                    activate BD
                    BD-->ET: Query OK
                    deactivate BD
                ET-->C: Query OK
                deactivate ET

            C->RO: response.redirect('/team/:team_id/members');
            deactivate C
        
        activate RO
        group 'TEAM-05'
        RO->C: getTeamMembers(request,response)
        deactivate RO
            activate C
            note right
            TEAM-05. 
            Consult Sequence Diagram
            end note
            C->V: response.status(200).json({success:true, body:members});
            deactivate C
    activate V
        end group
    V->V: showTeamMembers(members);
    V->V: showSuccessJoinMessage(team_id, employee_id, role);
    V->U: Updated view + success message
    deactivate V

alt Join Failed
            activate C
            C->V: response.json({success:false, body:error});
            deactivate C
    activate V
    V->V: showFailingJoinMessage(team_id, employee_id, role, error);
    V->U: Error message
    deactivate V
end

@enduml