@startuml
skinparam style strictuml

actor User as U
boundary "project_details.ejs" as V
boundary "projectDirectory.ejs" as PD
boundary "project.routes" as RO
control "project.controller" as C
entity "project.model" as M
database "unitas_system" as BD

autonumber

activate U
U -> V: Clicks "Delete Project" button
deactivate U

activate V
V -> V: displayConfirmationModal()
V -> U: Show confirmation modal
deactivate V

alt Confirms deletion? (no)
    activate U
    U -> V: Clicks "Cancel" / Closes modal
    deactivate U
    activate V
    V -> V: closeConfirmationModal()
    V -> U: Displays Project Details page (no changes)
    deactivate V
end
    activate U
    U -> V: Clicks "Confirm" button
    deactivate U
    activate V
    V -> V: captureProjectId(id)
    V -> RO: fetch('/project/:id_project/delete',{method: DELETE, headers:{'Accept': 'application/json'}})
    deactivate V

    activate RO
    RO -> C: deleteProject(request, response)
    deactivate RO

    activate C
    C ->> M: deactivate(project_id)
    activate M
    M ->> BD: execute('UPDATE project SET project.status='DISABLED' \nWHERE project.project_id=?;', [project_id])
        activate BD
        BD-->M: Query OK
        deactivate BD
    M-->C: Query OK
    deactivate M
    
    alt Project Deletion Failed

        C -> V: response.json({success: false, error: 'Could not delete project'})
        deactivate C
    activate V
    V -> V: displayErrorMessage(error)
    V -> U: Displays error notification
    deactivate V
    activate C
    end

        
        
        C -> RO: response.redirect('/project')
        deactivate C

        note right
        Render responsible under the 
        controller function getTeams.
        end note

@enduml