@startuml
|Admin|
start
:Clicks the “Delete” button in Role;
|System|
:Generates a confirmation popup;
|Admin|
:Clicks a button;
|System|
if(Did the Admin click the "Confirmation" button?) is (yes) then
else(no)
    if(Did the Admin click the "Cancel" button?) is (yes) then
        stop
    else(no)
    stop
    note right
        Return to Admin clicks a button
    end note
    end if
end if
:Sends a  request to substitute the account roles from the role to delete to Employee;
|Database|
:Performs the request;
|System|
:Sends a drop record request to the database;
|Database|
:Deletes the Role record from roles and roleprivilege;
|System|
:Gathers roles and privileges through queries;
|Database|
:Return the roles and privileges information;
|System|
:Renders the Role Administration page with updated information;
|Admin|
:Displays a success message;
stop

@enduml