@startuml

|User|
start
:Clicks the search bar;
|System|
if(Did the User click outside the search bar or touch ESC?) is (yes) then
    stop
else(no)
end if

|User|
:Types the name of the Employee, Team or Project;
|System|
if(Did the user click the “Search” button?) is (yes) then
    
else(no)
    stop
    note right
        Go back to Did the User click 
        outside the search bar or touch 
        ESC?
    end note
end if
|System|
if(Is the name input empty?) is (yes) then
    stop
    note right
        Go to User types the name.
    end note
else(no)
    |System|
    :Sends a query to the database with the name;
end if
|Database|
:Returns matching data;
|System|
:Verfies query results;
:Displays the first 10 matching results;
|User|
:Clicks a matching result;
stop


@enduml