@startuml

|User|
start
:Clicks the search bar;
|System|
if(Did the User click outside the search bar or touch ESC?) is (yes) then
    stop
else(no)
end if

|User|
:Types the name of the Employee, Team or Project;
:Clicks a button;
|System|
if(Did the user click the “Search” button?) is (yes) then
    
else(no)
    stop
    note right
        Go back to Did the User click 
        outside the search bar or touch 
        ESC?
    end note
end if
|System|
if(Is the name input empty?) is (yes) then
    stop
    note right
        Go to User types the name.
    end note
else(no)
    |System|
    :Sends a query to the database with the name;
end if
|Database|
:Returns matching data;
|System|
if(Are the results of the query > 0?) is (yes) then
    if(Did the query return > than 10 elements?) is(yes) then
        :Display the first 10 elements;
    else(no)
        :Display as many elements as the query returned;    
    end if
else(no)
:Display message "No matching result found";
stop
note right
    Go to User types the name
end note
end if

|User|
:Clicks somewhere;

|System|
if(Did the user click on a matching result?) is (yes) then
    :Redirect user to the result page;
    stop
else (no)
stop
note right
    Go back to Did the User click outside
    the search bar or touch ESC?
end note
end if


@enduml