@startuml
|User|
start
:Hovers or makes a click over the project Information button;

|System|
:Obtains project_id from the project page;
:Sends a query to obtain description, name, status, start_date, end_date and created_at to the database;

|Database|
:Returns the query;

|System|
:Verifies none of the information is null;
if(Is any of the information null?) then (no)
else(yes)
    |User|
    :Is informed an error has ocurred;
    stop
endif

|System|
:Creates a popover with the project information;
:Shows the popover;

|User|
:Passes the mouse or clicks outside the area of the project Information button;
stop

@enduml
