@startuml
skinparam activityFlowDirection Down

|User|
start
:Selects a Project page;

|System|
:Sends a query to retrieve the Project Achievements;
|Database|
:Returns the achievements information;
|System|
if(Did the system receive an error from the database?)is(yes)then
  |User|
  :Show error message ‘Error while obtaining project achievements;
  stop
|System|
else(no)
  if(Does the Project have Achievements?)is(yes)then

  else(no)
  :Stores the message: "This project has no achievements.";
  endif
endif
:Processes the achievements data;
:Renders the Project page;
|User|
:Visualizes the Project page;

stop
@enduml