@startuml
skinparam activityFlowDirection Down

|User|
start
:Clicks the “Leave Project” button over an Employee/Team;
|System|
:Displays a confirmation pop-up;
|User|
:Click a button;
|System|
if(Did the User click the ‘Confirm’ button?)id(yes)then

else(no)
  |System|
  :Close pop-up;
  stop
endif

|System|
:Sends a request to remove content from the project;
|Database|
:Updates the collaboration or teamProject entry;
|System|
if(Was the user successfully removed?)is(no)then
  |User|
  :Displays "Unable to leave the project";
  stop

else(yes)
  |System|
  :Retrieves the updated Project information;
  if(Did the database return an error?)is(yes)then
    |User|
    :Show error message “Team deletion has failed”;
    stop
  else(no)
  endif
endif

|System|
:Renders the Project page;
|User|
:Shows the success message;

@enduml