@startuml
|User|
start
:Clicks "Delete Project" button;

|System|
:Displays confirmation modal;

|User|
if (Confirms deletion?) is (yes) then
    |System|
    :Sends a deletion request with the project_id to the Database;
else (no)
    |System|
    :Closes modal;
    |User|
    :Displays Project Details page (no changes);
    stop
endif


    
    |Database|
    :removes the project record and its relational dependencies (participants/tasks);
    
    |System|
    if (Did the System receive an error from the database?) is (no) then

    else(yes)
        |User|
        :Displays 'Error: Could not delete project' message;
        stop
    endif


|System|
:Updates the Project page;
|User|
:Displays 'Project Deleted Successfully' notification;
stop
@enduml