@startuml
|User|
start
:Clicks the Join button;

|System|
:Retrieves the employee_id from the authenticated session;
:Obtains the project_id from the Project Page;
:Sends a query to verify whether the User is already registered as an individual participant in the selected Project;

|Database|
:Returns the query;

|System|
:Verifies the User is not already registered in the selected Project;
if (Is the User already registered as an individual participant in the selected Project?) then (yes)
|User|

    :Informs the User they are already part of the Project;
    stop
else (no)
|System|
    :Creates a new Collaboration object;
endif

|Database|
:Stores the Collaboration information;

|System|
if (Was the Collaboration object stored successfully?) then (yes)
    :Gathers Project information through queries;
else (no)
|User|  
    :Informs the User an error has occurred;
    stop
endif

|Database|
:Returns queries response;

|User|
:Views the Project Page with updated information;
stop
@enduml