@startuml
|User|
start
:Clicks the "Delete" button of a Project Achievement;

|System|
:Generates a confirmation dialog for the deletion;

|User|
:Clicks a button;

if(Did the User click the ‘Confirm’ button?)is(yes)then
    |System|
    :Sends a query to delete the ProjectAchievement object;
else(no)
    |System|
    :Close pop-up;
    stop
endif



|Database|
:Deletes the ProjectAchievement object;

|System|
if (Was the ProjectAchievement object deleted successfully?) then (yes)
    :Gathers Project information through queries;
else (no)
    |User|
    :Sees an error message on the Project Page;
    stop
endif

|Database|
:Returns the Project information;
|System|
if(Did the database return an error?)is(yes)then
    |User|
    :Show error message Achievement deletion has failed”;
    stop
  else(no)
  endif
|System|
:Renders the Project Page with updated information;

|User|
:Sees the Project Page without the deleted Achievement;
:Display success message;

stop
@enduml