@startuml
|User|
|System|
START
:Unifies report data into filters_json;
:sends a petition to the AI API with prompt, filters_json, input_snapshot_json;
:Sets counter = 0;
|AI API|
:Processes the petition;
|System|
:Increase counter +1;
:Receives the response from the AI API;
if(Did the System receive an error message from the API?) is (yes) then
  |System|
  if(Is counter < 3?) is (yes) then
  stop
  note left
    Go to System sends a petition to the AI API  
  end note
  
  else(no)
  endif
  |System|
else(no)
endif
stop


@enduml