@startuml
skinparam activityFlowDirection Down

|Lead|
start
:Register Team;

|System|
:Show form;

|Lead|
:Enter team data;
:Submit;

|System|
:Validate input;

if (Valid?) then (Yes)

  :Check name;

  if (Name exists?) then (Yes)
    |Lead|
    :Show name error;
    stop
  else (No)


    |System|
    :Init team (id, time);
    :Send INSERT query to database;

    |Database|
    :Execute query and store new Team record;

    |System|
    if (Saved?) then (Yes)
      |Lead|
      :Show success;
    else
      |Lead|
      :Show error;
    endif

  endif

else (No)
  |Lead|
  :Show validation error;
  stop
endif

stop
@enduml