@startuml
|Lead|
start
:Clicks the “Delete” button in the Team page;
|System|
:Generates a confirmation popup;
|Lead|
:Clicks a button;
|System|
if(Did the Lead click the “Confirmation” button?)is(yes)then

else(no)
    if(Did the User click the “Cancel” button?)is(yes)then
        stop
    else(no)
        stop
        note right
        Return to Did the Lead click
        the “Confirmation” button
        end note
    endif
endif

|System|
:Sends a modify record request to the database;
|Database|
:Changes status of the Team from teams;
|System|
if( Did the database return an error?)is(yes)then
    |Lead|
    :Show error message 'Team deletion has failed';
    stop
    |System|
else(no)
endif

|System|
:Gathers Teams of the Lead through queries;
|Database|
:Returns the Teams information;
|System|
if( Did the database return an error?)is(yes)then
    |Lead|
    :Show error message 'TIntermediate Team cound not load';
    stop

else(no)
endif
|System|
:Renders the Intermediate Team page with updated information;
|Lead|
:Display a success message;
stop
@enduml