@startuml
|User|
start
:Clicks the “Add” button in the Team Members module;
|System|
:Generates a popup to search for an employee and write their role in the team;
|User|
if(Did the User click the “Close” button?) is (yes) then
    stop
else(no)
:Writes an employee name in the search bar;
:Submits the search by clicking the "Search" buttton;
|System|
:Sends a query with the employee name to database;
|Database|
:Returns matching employees;
|System|
:Shows query results;
|User|
if(Did the User select an Employee from the search?) is (no) then
    |User|
    stop
    note left
    Return to User writes an Employee name in the search bar
    end note
    
else(yes)
    

end if
|User|
:Enters its role as a string;
    if(Is the role input empty?) is (yes) then
    |System|
    :Button "Save" stays disabled;
    stop
    note right
        Return to User enters its role as string
    end note
    

    else(no)
    |System|
    :Button "Save" is enabled;
    end if
|User|
:Submit its role by clicking the Save button;
|System|
:Creates a new EmployeeTeam object;
|Database|
:Stores the EmployeeTeam information;
|System|
:Gathers Team information through queries;
|Database|
:Returns queries response;
|System|
:Renders the Team Page with updated information;
stop
@enduml