@startuml
|User|
start
:Clicks the Join Button;
|System|
:Retrieves the employee_id from the authenticated session;
:Generates a popup asking the user's role in the team;
|System|
if(Did the User click the “Close” button?) is (yes) then
    stop
else(no)
    |User|
    :Enters its role as a string;
    :Clicks the Save button;

    |System|
    if(Is the role input empty?) is (no) then
    |System|
    :Accepts the User input;

    else(yes)
    |System|
    :Button "Save" gets disabled;
    :Shows the message “Some obligatory fields are empty”;

    stop
    note right
        Return to User enters its role as string
    end note
end if

:Creates a new EmployeeTeam object;
|Database|
:Stores the EmployeeTeam information;
|System|
:Gathers Team information through queries;
|Database|
:Returns queries response;
|System|
:Renders the Team Page with updated information;
stop
@enduml