@startuml
skinparam activityFlowDirection Down

|User|
start
:Accesses the Team page;

|System|
:Retrieves team_id from the Team page;
:Gathers projects through queries;

|Database|
:Returns the project's information;

|System|
if(Did the system receive an error from the database?)is(yes)then
  |User|
  :Show error message ‘Error while obtaining team projects’;
  stop
|System|
else(no)
  if(Did the System receive more than one project information?)is(yes)then

  else(no)
    :Store text “There are no projects in the current team”;
  endif
endif

|System|
:Renders Team page;

|User|
:Visualized Team page;

stop
@enduml