@startuml
skinparam ActivityDiamondMaxWidth 100
skinparam Padding 5

|User|
start
:Accesses a Team page;

|System|
:Captures the current team_id;
:Sends query fetch the member Employee details;

|Database|
:Returns the employee's full_name, role, and started_at;

|System|
if(Did the system receive an error from the database?)is(yes)then
    |User|
    :Show error message 'Error while obtaining team members';
    stop
    |System|
else(no)
    if (Did the System receive more than one employee information?) is (yes) then

    else (no)
        |System|
        :Store text “There are no members in the current team”;
    endif
endif
|System|
:Processes the data;
:Renders the Team page;
|User|
:Displays Team page;
stop
@enduml